### PR TITLE
Mac: Improve fonts metrics and line drawing

### LINKED ISSUE #54: Selection area doesn't cover selected text in full
Selection area doesn't cover selected text in full
Screenshot 2020-04-09 at 00 58 04

### PR DESCRIPTION
**Pull request by krzyzanowskim**
Fixes #54 

In this PR:
- Selection highlight in pair with displayed glyphs

    - before
        Screenshot 2020-04-09 at 00 58 04

    - after
        Screenshot 2020-04-09 at 02 07 06

- dynamic line-height support

    - before
        Screenshot 2020-04-10 at 12 53 52

    - after
        Screenshot 2020-04-11 at 21 19 04

- Improved support for font metrics. Calculate lines positions based on used font (no more magic offset values)
- Sharp background frame - `fullBackgroundColor` attribute
    - before

    - after

### CODE REVIEW

**Comment by migueldeicaza** [comment]
I think this is failing due to the move to put the assorted fonts inside "font":

```
2020-04-09T04:19:42.7993220Z /Users/runner/runners/2.168.0/work/SwiftTerm/SwiftTerm/SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift:182:51: error: use of unresolved identifier 'fontNormal'
2020-04-09T04:19:42.7993400Z         let lineHeight: CGFloat = CTFontGetAscent(fontNormal!) + CTFontGetDescent(fontNormal!) + CTFontGetLeading(fontNormal!);
2020-04-09T04:19:42.7993530Z                                                   ^~~~~~~~~~
2020-04-09T04:19:42.7994530Z /Users/runner/runners/2.168.0/work/SwiftTerm/SwiftTerm/SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift:182:83: error: use of unresolved identifier 'fontNormal'
2020-04-09T04:19:42.7994690Z         let lineHeight: CGFloat = CTFontGetAscent(fontNormal!) + CTFontGetDescent(fontNormal!) + CTFontGetLeading(fontNormal!);
2020-04-09T04:19:42.7994790Z                                                                                   ^~~~~~~~~~
2020-04-09T04:19:42.7995380Z /Users/runner/runners/2.168.0/work/SwiftTerm/SwiftTerm/SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift:182:115: error: use of unresolved identifier 'fontNormal'
2020-04-09T04:19:42.7995550Z         let lineHeight: CGFloat = CTFontGetAscent(fontNormal!) + CTFontGetDescent(fontNormal!) + CTFontGetLeading(fontNormal!);
2020-04-09T04:19:42.7995670Z                                                                                                                   ^~~~~~~~~~
2020-04-09T04:19:42.7996240Z /Users/runner/runners/2.168.0/work/SwiftTerm/SwiftTerm/SwiftTerm/Sources/SwiftTerm/Mac/MacTerminalView.swift:184:106: error: use of unresolved identifier 'fontNormal'
2020-04-09T04:19:42.7996390Z         let attributedString = NSAttributedString(string: "W", attributes: [NSAttributedString.Key.font: fontNormal!])
2020-04-09T04:19:42.7996530Z                                                                                                          ^~~~~~~~~~
2020-04-09T04:19:42.7996580Z 
```

**Comment by krzyzanowskim** [comment]
Don't merge this one, it has side effects I need to address

**Comment by krzyzanowskim** [comment]
Ready!

**Comment by migueldeicaza** [comment]
I noticed an interesting idiom here, to remove the TerminalDelegate implementation from the TerminalView, and then implement it as an extension.  Is that a common idiom?

**Comment by krzyzanowskim** [comment]
> I noticed an interesting idiom here, to remove the TerminalDelegate implementation from the TerminalView, and then implement it as an extension. Is that a common idiom?

That's something not unusual. Here, in particular, I moved it to the extension to separate it visually

**Pull request merged**
