### PR TITLE
fix true color display

### PR DESCRIPTION
**Pull request by lvht**

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Can you explain this change?

The colors are passed as 16-bit values, and I am wondering why you end up with 8 bit values.

**Comment by lvht** [comment]
I use the master branch, and it does not display ture color at all. It seems the r,g,b has a range of  0-255

**Comment by lvht** [comment]
The class Color's  red/green/blue do have a range of 0-65535. And the Attribute.trueColor is defined as
```swift
        /// This means that the color has been configured to be a 24-bit true color
        /// and has 8 bits for red, green and blue
        case trueColor(red: UInt8, green: UInt8, blue: UInt8)
```

**Comment by lvht** [comment]
BTW, this is an awesome project to use and to learn. Would you like move SwiftTerm to a dedicate project? It seems that the github.com/SwitfTerm is available.

**Comment by migueldeicaza** [comment]
Can you provide me with the test case?

Will review later today!

And no, I do not think I want to move this to a separate organization.

**Comment by migueldeicaza** [comment]
@lvht I do not appreciate the creation of a SwiftTerm organization, please delete it.

**Comment by lvht** [comment]
I will do independent on the new organization.

**Comment by migueldeicaza** [comment]
@lvht that is really poor form to fork someone else's project and hijack the name.

**Comment by migueldeicaza** [comment]
I finally had time to review this, it is indeed 0..255, applied your fix.

**Pull request closed without merging**
